language: python
python:
  - "3.6"

services:
  - docker

before_script: pip install docker-compose

script:
  - docker-compose run pa_app sh -c "flake8"
  - docker-compose run pa_app sh -c "./wait-for-it.sh pa_db:3306 -t 180 --strict -- python -m unittest discover -s tests"   