version: '3.1'

services:

  pa_app:
    build: .
    container_name: pa_app   
    volumes:
      - .:/code
    tty: true
    depends_on:
      - pa_db

  pa_db:
    container_name: pa_db    
    restart: always        
    environment:      
      MYSQL_ROOT_PASSWORD: mypassword    
    volumes:
      - ./src/sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro