version: '3.1'

services:

  pa_app:    
    tty: true
    depends_on:
      - pa_db

  pa_db:    
    environment:      
      MYSQL_ROOT_PASSWORD: mypassword    
    volumes:
      - ./src/sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro