# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
        environment:
            DB_NAME_OLPT: pa_oltp
            DB_USER_OLTP: pa_oltp
            DB_PASS_OLTP: mypassword
      - image: circleci/mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: mypassword
            MYSQL_DATABASE: pa_oltp
            MYSQL_USER: pa_oltp
            MYSQL_PASSWORD: mypassword
            

    working_directory: ~/repo

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      - run:
      # Step 2: Our primary container isn't MYSQL so run a sleep command until it's ready.
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      # Step 3: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt            
      # Step 4: run linter
      - run:
          name: run linter
          command: |
            . venv/bin/activate
            flake8 --exclude=venv* --statistics
      # Step 5: initialize db   
      - run: 
          name: initialize db 
          command: |
            . venv/bin/activate
            python src/db_init.py
      # Step 6: run tests   
      - run: 
          name: run tests 
          command: |
            . venv/bin/activate
            python -m unittest discover -s tests
            