# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7        
      - image: circleci/mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: mypassword
            MYSQL_DATABASE: pa_oltp
            MYSQL_USER: pa_oltp
            MYSQL_PASSWORD: mypassword
            

    working_directory: ~/repo

    steps: # steps that comprise the `build` job
      - checkout # check out source code to working directory
      # Run a step to setup an environment variable.
      - run: 
          name: "Setup custom environment variables"
          command: |
            echo 'export DB_NAME_OLPT="pa_oltp"' >> $BASH_ENV # Redirect into $BASH_ENV
            echo 'export DB_USER_OLTP="pa_oltp"' >> $BASH_ENV # Redirect into $BASH_ENV
            echo 'export DB_PASS_OLTP="mypassword"' >> $BASH_ENV # Redirect into $BASH_ENV
      - run:
      # Our primary container isn't MYSQL so run a sleep command until it's ready.
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      # Create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt            
      # Run linter
      - run:
          name: run linter
          command: |
            . venv/bin/activate
            flake8 --exclude=venv* --statistics
      - run:
          name: "What was my custom environment variables?"
          command: 
            echo ${DB_USER_OLTP}
            echo ${DB_PASS_OLTP}
            echo ${DB_NAME_OLTP}
      # Initialize db   
      - run: 
          name: initialize db 
          command: |
            . venv/bin/activate
            python src/db_init.py
      # Run tests   
      - run: 
          name: run tests 
          command: |
            . venv/bin/activate
            python -m unittest discover -s tests
            